apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cypress-reporting
  labels:
    app: cypress-reporting
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: cypress-reporting.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cypress-reporting
                port:
                  number: 80
