apiVersion: v1
kind: Service
metadata:
  name: cypress-reporting
  labels:
    app: cypress-reporting
spec:
  type: ClusterIP
  selector:
    app: cypress-reporting
  ports:
    - name: http
      port: 80
      targetPort: 5000
